language: node_js
node_js: '8'
sudo: required
services:
- docker
install: npm install
script:
- npm test
- npm run coverage
after_success:
- "./.travis/after_success.sh"
env:
  global:
  - secure: f0swVJlzYixBEq7mi8AP/Fh2IIbJ5TfqzYoQGmHUtbiFmVJlhU9SKwea4QYEgfK2x0CNmryBCVfuYj36QkR+cNuuj9+JFeSnxmECxWOAyLCXW1L21+si6+QBHrgafi6C6mSg6O4OyaWBgOpUHHmCBVpYgxJi8FUZcGsnYnHWgpTPuHA2nIsV1EuPOn2CJZ6o57ZVp20INmc1iUUIlZQ30k0XlZELLJsTZiTzLuQGhrz3QgiGB6icDVV6GWUO1rMZHJZ8VmX+vNMb/pTHZTuLjvcfbrvVw6WKy+yOIed38oCg4rXnWgzyVE5PjpZLwc8cDdHyREqsL69vjaonhWq+bdTy3t5/JXnOqcCDUULI+pk5+5RTzoX3Z0bsKeAkAhp94ofoJ7wMb5PQh1wfs8m+8+NuIgeLLBBQqjxNKJCVBE7gOPjpgh0pj3YXXXjKK6cayPxiK7I/1peiH+fChqJtILq4loNCogUH141jQIoiQP4nriGlKFwZpvy0dtNvfYYzVxDBVQFoYDbUjjZwFu1yxBfalEskrR6XisVPg/hjHuVwOZtU1nCvG2THMBcQhmk4CWDgf5U8NSChbGqrz/11/28pVimPxYVldZYx59zgg2ednMv1La7TLuUIlFvPyTHJwkCb3cCAQf0tv9tjnXAfEKkyK2d1RqYdxVIIX2V0SYM=
  - secure: j+BXbCxnet3cD42+GW345x0yTt86oLWI6halSG9HwC1quTc/8IKe7q5NRtcJ7Laul8Hbmob2UUMK+HH6PKKU7FXOx/KwPYh1tJsJSq7Bd0k1FbPkedfYfJH4k9zhcqGI0yGH77r+xAA236aNIUKWLa5TchSCHiRsI9hq6GlUr4EcjdoHSQ6rgjiIksjyWRt70mCTvNp2Ern6Ifm0uPV/6SAB9sGjoAycFz5Ui50dMh9VE2E9YbNvk8uAvILdFhcdwEoNBCAJ9HCWSvCU4g8CbimBjN62HOmpbDfdeHcKEO3IuFqyGmZOP6urWgRE8MQ263nXWvupu8g37sMf510/G6HEcFrgA1v9vTdajGOvDhUmMMRRefUS1XRJB4zvcz20srMAItckBhjRJeRAi1UVQzS2Ph1+7CYyS9eUtmN3O53bTXkQ1WQ8WoaKd7EWps1wUmDz4509HJPMtmdIIXOng991lIHrmiSAXxNIRsZ5klqI11mPnPsYbuJWuZUOEyhr7wPJU8Wq7ne02IFHysB1aJkb1lYlnP0kjaC2IieZqm9qMpqoHAlvrf5K+92kmRfazXowQ0xXeK7TE6LflpaO2JlBlzpPDCh+p95G3Q+Z/lkmUuZVhZGZM03vH3FEJIB1XBA8R9v6FX+k0DW8UXbavjgcD4WK8iab/dvhXvWseso=
