language: node_js
node_js: '8'
sudo: required
services:
- docker
install: npm install
script: npm test
after_success:
- npm run coverage
- docker build -t fetmar/elevator:latest . --build-arg GIT_SHA=`git rev-parse --short HEAD`
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
- docker push fetmar/elevator:latest
env:
  global:
    secure: tgAgIWH6qzIM4L7dw8i+tTTT3OOAc2ccrzwn69HEsPLuP1oJzV0hmatiSb16wV/EfCWMXt32L8tWj+J5qJl0OvDI8s3z9tjQwAbPnLoX72JKXZgpMQu6BxY6fjKI2wVUweCVzV1oa99Fs2c6rzW0R1bz9Nzh2WYm5zsmJZHQTIoFEpct1uOolbdoZEUY3jCZGoiqY97HTOH9ZOGds1D0Fmt7IzKu42tggTw+ZTrmAVIIHNSedJ5P3GOv9s66IXBuIe1536iaViEwNXAnlUPC8OhIEfF3U3BlE1KFDWce2Niih3iWxd2vtxobPYGIZabKr7cd7QRU51phb1ancnuLKard4hHXxdPnU2zOxg8UHCP6VHL6iffZfvZh5oOXI2UyRvbWBrbN5eyf2SCOVy8vSqW9E0oiao4gsDYzPo5OIZ7mWJBsqWXx5I/HyGpFgvFtXSerjyYWf2kGpT6T3CekNQvy1f1vACUCOppV0Wp/mj9KC/6UnFDAnBkZivXVg4VkQ/LzMR/zQX8kPuLEhFN7W4Wppf988Pg9KGnf6tSmxefkyt5pqoOb0oVKUP/AVDdgqfAJho69C50+fj7HFxAFyWGw3MlaEd8m+83417AZxaxNgCRrlFTunec5+ymtytDLMniGNK77pfLgV+B4AWz5haAUeoWZgzm4p8ZN2z/gyt8=
    secure: rfh/I/EugduW6CtqMi5Lo5ctutyfSMVsi20DRBbxSuFeSJyGSouhKyrAa9wqJ9wZfYx57PUdaOQUaxhj4NSmQQkQx8W8ZD/aZakYwcTVu1ettwtryrQrp/xYVBtvL+J4uZbhnJX+VbpU1aaRFZEUO4+PXH+ieMspGYlm2SUAEZWcEs83ryjpgA5AUjKWXlh4BgTJhfzTa/F5BujbsXNpPF+ObDLa7qEASBqXMz+aBMFhGO4ZpAjxZ31e+dix3wy8QffSwHROvtCxw7y5Xl5Xpw2nURxsmNM3+/Bg/VK6GfCUq8xjuNrW0VAj9ixukETJuO0SyL59sdWoM1x14LHUdvqsi0KNFMUCYOO/5LZvkqIbu3v3S02qGK+3cRh8hK1RUTo/XRXkLWgLRjnuAV3SCPrdJz6aPH8KwdRyqLnrJmF5Dw+cooLP7hjqehaXruF6dODZ8zyb4eagQSjdiEymFRvakC5CLe5gfW03TIM2aUwaSTVc6a4NjPH8BbyxD+MwcaIuqYK1shtuyqjj0p8dbtujyOu1X0L2UZBFZOCKuMyzs5KJOOqoe69bbafjrKpUd2bAVAZHKnDvyV5D8F2ZLXOPbrI8nVuFM/BbdXe8kbpuTSSR3O3s1+8/YGEQInGpcptJoX+Crs4D/MXRmv6mtnMeWxK+oaifFrdxd+Qn1Ag=
