language: node_js
node_js: "8"
sudo: required
services:
  - docker

install: npm install
script: npm test
after_success:
  - npm run coverage
  - docker build -t fetmar/elevator:latest .
  - docker push fetmar/elevator:latest

docker:
  pass:
    secure: ZB0e/dPIPwTlM6AnwfJEkGdnM2LjLpS/diy591S4r0VguRVxznIoCpwvtcjRNoJA8QreOK1heHjpmI8j3X2DQFw83/wL0v8cbLgX1fWgFbleYrroDGp7g3wg6DjOfy7zX5+ZuhxvCrvO1u10UhShhmniGIuWCWvt3q1BgSBUpa4DwCky5aUj13MI8RzJNl4EAyIFL+hMY7gNyooqa99iBT9GTLXAkZnasv04++Yll3rZ3h1zV29AEJMarT87tjGqTV+AUk1X4XKc9IPnVqXF2mT5yJs2mwu/PAXeItbkQ4kvnWLKuQOHU/EKwVPpdLDYsOmdoc4lCpsMYm84f0MOJEmNtcXVYXXhNpgHUZFExMQkEeSVE+D8O6eszI0a8x7oz7YfnH2tTwJUvffYoMwHccLZJhqhuFWXzen7LWmu0XL2IcgdKbItGrW0NR2xaR68H1bWJgjIIev9VsYVEWDg+zx5JCcV0HtP0zbZm2JuGApkm7eC8Is08bHenrCV9mb7B2aJirl6kuaQ8CBGFbeHwDLnJGRjoiRAr1ctzf72gI/48QIOH8y/9Elu7Q+vVFcEN6mz9mKp9Xj2vPCuVrCsX1JslN4yUy+L+UU1x/wUP7o35nyai+Bn830HOAzAf6P2JiP55Gti9vbeYjZWDclwuj3Z0XVCxai1v/1kcFP0tOY=
  user:
    secure: V/54FRyBXG8wtq2lGppdf/A7dpyHaibA9vVX2tVhMrvVXfnRP66+Fl1EvszuXMy3rHAmbOtiN0fjplQiswvs9wZxLtIGtgDJVsRZI2M40eKX7O4PZhmk+0tiGxkJL10mx11h7u273Vsf/XlxEV5Jckp87pOAqtsYPcgwLcDr9UvgJxePe+TadTyEQHhAX0VERyqi8LgwNpteF4rmM45T5C1OWZOeFIwqtTJ33I4GpH5AJPlStVLwJFtpMOS7LjDsLaz5M6UjQ5sQMalS5Dszf6bBKZ0rT2MXHpqRQUkhCZwjEZWjzFnEysTjhua9jrlUX5PRLPuCgaSIK72DYZ3tMiQy9tSC3ZmMHCiy1GgGUKDQUmi49YxlrM8zyX6hn5Sg5WB2t3WA/T+cymctJftmZ+sUErNbunYOfEaPBBPMccCWIg7yFnqTRbjOcc+v8XMKQZhd+YiyWQMeGHUqd15TRqksv0c/MQXDmtakAr4A8vmMECBlCDNqsEmhwn0zFcJSlB0di5Cx22oBNAa4K/LB/L/HkfAxEOQ4smJSR1sFdClnStlrhY/jpEut0BDbQYQk9/WSiYIDCyp/rSMyA6qgkfBXFHXMG3xeR8mteSZ9+/zfeA2YmYJ0iEyjC9pDNIft6GVO/8MOuXH8+aViA16CGzfawHnVHFSGRwN5xUqrkoQ=
